/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author germa
 */
public class Consulta extends javax.swing.JPanel {
    
    
    boolean banderaMin=false;
    boolean banderaMax=false;
    
    /**
     * Creates new form Alta
     */
    public Consulta() {
        initComponents();
        TableColumn columna = jTable1.getColumnModel().getColumn(0);
        columna.setMaxWidth(0);
        columna.setMinWidth(0);
        columna.setPreferredWidth(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModificarInmueble = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAltaInmueble = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelId = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        comboBox1 = new javax.swing.JComboBox();
        comboBox2 = new javax.swing.JComboBox();
        comboBox3 = new javax.swing.JComboBox();
        label3 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        comboBox4 = new javax.swing.JComboBox();
        label4 = new javax.swing.JLabel();
        labelId1 = new javax.swing.JLabel();
        textFieldId2 = new javax.swing.JTextField();
        textFieldId3 = new javax.swing.JTextField();
        labelId2 = new javax.swing.JLabel();
        labelId3 = new javax.swing.JLabel();
        comboBox5 = new javax.swing.JComboBox();
        label5 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jButtonModificarInmueble.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButtonModificarInmueble.setText("Modificar");
        jButtonModificarInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarInmuebleActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Checkbox", "Propietario", "Localidad", "Dirección", "Superficie", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableColumn columna = jTable1.getColumnModel().getColumn(0);
        columna.setMaxWidth(0);
        columna.setMinWidth(0);
        columna.setPreferredWidth(0);
        jTable1.setFocusable(false);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButtonAltaInmueble.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButtonAltaInmueble.setText("Eliminar");

        jButtonAtras.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 18))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(218, 456));

        labelId.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelId.setText("Cantidad de dormitorios");

        textFieldId.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        textFieldId.setToolTipText("Ingrese solo números");
        ((AbstractDocument)textFieldId.getDocument()).setDocumentFilter(new LimitadorTextField(2));

        /*String[] listaNombresDeportes = gestor.GestorCD.getListaDeportes();
        String[] listaND= new String[listaNombresDeportes.length+1];
        listaND[0]="";
        for(int j=0; j<listaNombresDeportes.length; j++){
            listaND[j+1]=listaNombresDeportes[j];
        }
        Arrays.sort(listaND);*/
        comboBox1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        comboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "En 2", "3" }));

        comboBox2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        comboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Creada", "Planificada", "En disputa", "Finalizada" }));

        comboBox3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        comboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "3" }));

        label3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        label3.setText("Barrio");

        label2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        label2.setText("Ciudad");

        label1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        label1.setText("Provincia");

        jButtonBuscar.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        comboBox4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        comboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "3" }));

        label4.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        label4.setText("Tipo");

        labelId1.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelId1.setText("Min");

        textFieldId2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        textFieldId2.setToolTipText("");
        ((AbstractDocument)textFieldId2.getDocument()).setDocumentFilter(new LimitadorTextField(15));

        textFieldId3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        textFieldId3.setToolTipText("");
        ((AbstractDocument)textFieldId3.getDocument()).setDocumentFilter(new LimitadorTextField(15));

        labelId2.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelId2.setText("Precio");

        labelId3.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        labelId3.setText("Max");

        comboBox5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        comboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1", "3" }));

        label5.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        label5.setText("Estado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(label1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelId1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldId2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelId3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldId3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelId2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3)
                    .addComponent(comboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelId2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFieldId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelId3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelId1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButtonBuscar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        textFieldId.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (!Character.isDigit(keyChar)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
        textFieldId2.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char tecla = e.getKeyChar();

                if (!Character.isDigit(tecla)) {
                    if ('.'==tecla){ // VER PUNTO
                        if (banderaMin){
                            getToolkit().beep();
                            e.consume();
                        }
                        else banderaMin=true;
                    }
                    else{
                        getToolkit().beep();
                        e.consume();
                    }
                }
                // Buscar en la cadena al eliminar
            }
        });
        textFieldId3.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char keyChar = e.getKeyChar();
                if (!Character.isDigit(keyChar)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jButtonAltaInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificarInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAtras)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonModificarInmueble)
                                .addComponent(jButtonAltaInmueble))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jPanel2.getAccessibleContext().setAccessibleName("Filtros");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarInmuebleActionPerformed

        int row = jTable1.getSelectedRow();

        if(row == -1){
            JOptionPane.showMessageDialog(null,"Debe seleccionar un inmueble",
                "Error", JOptionPane.INFORMATION_MESSAGE);
        }

        else{

            String nombre=jTable1.getValueAt(row, 0).toString();
            String deporte=jTable1.getValueAt(row, 1).toString();
            String modalidad=jTable1.getValueAt(row, 2).toString();
            String estado=jTable1.getValueAt(row, 3).toString();
            
            /*
            int idComp=GestorCD.obtenerIDCD(nombre);

            CompetenciaAux elem=listaprueba.get(row);

            CompetenciaAux compAux= new CompetenciaAux(estado, deporte, modalidad,
                nombre, elem.getFormaPuntuacion(), idComp);
            GestorVentanas.get().verCompetencia(compAux);*/
        }

    }//GEN-LAST:event_jButtonModificarInmuebleActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        GestorVentanas.get().remove(this);
        GestorVentanas.get().menuVolver();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(comboBox1.getSelectedIndex()==0 && comboBox3.getSelectedIndex()==0 &&
            comboBox2.getSelectedIndex()==0 && textFieldId.getText().isEmpty()){
            errorFiltros();
        }
        else{
            // Llamar a la funcion para rellenar la tabla (devuelve matriz)
            /*Object estado = comboBoxEstado.getSelectedItem();
            String textEstado = String.valueOf(estado);
            Object deporte = comboBoxDeporte.getSelectedItem();
            String textDeporte= String.valueOf(deporte);
            Object modalidad = comboBoxModalidad.getSelectedItem();
            String textModalidad= String.valueOf(modalidad);

            String nombre=textFieldCompetencia.getText();

            if("".equals(textDeporte)){textDeporte=null;}
            if("".equals(textEstado)){textEstado=null;}
            if("".equals(textModalidad)){textModalidad=null;}

            if("".equals(textFieldCompetencia.getText())){
                nombre=null;
            }

            // Se recuperan las competenciasAux de la base de datos
            listaprueba = GestorCD.listarCD(nombre, textDeporte,textModalidad,textEstado);

            // Eliminacion de la tabla actual
            DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
            int filas=jTable1.getRowCount();
            int i;
            for (i=0;filas>i; i++) {
                modelo.removeRow(0);
            }

            // Se le asignan las competencias recuperadas
            for(i=0;i < listaprueba.size();i++){

                CompetenciaAux elem=listaprueba.get(i);

                String fila[]=new String[4];

                fila[0]= elem.getNombre();
                fila[1]= elem.getDeporte();
                fila[2]= elem.getModalidad();
                fila[3]= elem.getEstado();

                modelo.addRow(fila);
            }
            jTable1.setModel(modelo);

            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"No se han encontrado resultados.",
                    "Error", JOptionPane.INFORMATION_MESSAGE);
            }*/
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    
    private void errorFiltros(){
        JOptionPane.showMessageDialog(null, "Ingrese un filtro de busqueda", "", JOptionPane.INFORMATION_MESSAGE);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboBox1;
    private javax.swing.JComboBox comboBox2;
    private javax.swing.JComboBox comboBox3;
    private javax.swing.JComboBox comboBox4;
    private javax.swing.JComboBox comboBox5;
    private javax.swing.JButton jButtonAltaInmueble;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonModificarInmueble;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelId1;
    private javax.swing.JLabel labelId2;
    private javax.swing.JLabel labelId3;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldId2;
    private javax.swing.JTextField textFieldId3;
    // End of variables declaration//GEN-END:variables
}
