package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0



import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private Vendedor vendedor;
     private String nombre;
     private String apellido;
     private Integer telefono;
     private String email;
     private Set inmuebles = new HashSet(0);
     private Set consultas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(int idCliente, String Nombre){
    this.nombre=Nombre;
    this.idCliente=idCliente;
    
    }
    
    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }
    
    public Cliente(int idCliente, Vendedor vendedor, String nombre, String apellido, Integer telefono, String email, Set inmuebles, Set consultas) {
       this.idCliente = idCliente;
       this.vendedor = vendedor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.email = email;
       this.inmuebles = inmuebles;
       this.consultas = consultas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


