package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0



/**
 * ConsultaId generated by hbm2java
 */
public class ConsultaId  implements java.io.Serializable {


     private int idCliente;
     private int idInmueble;

    public ConsultaId() {
    }

    public ConsultaId(int idCliente, int idInmueble) {
       this.idCliente = idCliente;
       this.idInmueble = idInmueble;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public int getIdInmueble() {
        return this.idInmueble;
    }
    
    public void setIdInmueble(int idInmueble) {
        this.idInmueble = idInmueble;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsultaId) ) return false;
		 ConsultaId castOther = ( ConsultaId ) other; 
         
		 return (this.getIdCliente()==castOther.getIdCliente())
 && (this.getIdInmueble()==castOther.getIdInmueble());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCliente();
         result = 37 * result + this.getIdInmueble();
         return result;
   }   


}


