package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private ConsultaId id;
     private Cliente cliente;
     private Inmueble inmueble;
     private Date fechaEmision;

    public Consulta() {
    }

	
    public Consulta(ConsultaId id, Cliente cliente, Inmueble inmueble) {
        this.id = id;
        this.cliente = cliente;
        this.inmueble = inmueble;
    }
    public Consulta(ConsultaId id, Cliente cliente, Inmueble inmueble, Date fechaEmision) {
       this.id = id;
       this.cliente = cliente;
       this.inmueble = inmueble;
       this.fechaEmision = fechaEmision;
    }
   
    public ConsultaId getId() {
        return this.id;
    }
    
    public void setId(ConsultaId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Inmueble getInmueble() {
        return this.inmueble;
    }
    
    public void setInmueble(Inmueble inmueble) {
        this.inmueble = inmueble;
    }
    public Date getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }




}


