package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Edificio generated by hbm2java
 */
public class Edificio  implements java.io.Serializable {


     private int idEdificio;
     private Boolean propiedadHorizontal;
     private Integer antiguedad;
     private Integer superficie;
     private Integer banios;
     private Boolean garage;
     private Boolean patio;
     private Boolean aguaCorriente;
     private Boolean piscina;
     private Boolean cloacas;
     private Boolean gasNatural;
     private Boolean pavimento;
     private Boolean lavadero;
     private Boolean aguaCaliente;
     private Integer telefono;
     private Set inmuebles = new HashSet(0);

    public Edificio() {
    }

	
    public Edificio(int idEdificio) {
        this.idEdificio = idEdificio;
    }
    public Edificio(int idEdificio, Boolean propiedadHorizontal, Integer antiguedad, Integer superficie, Integer banios, Boolean garage, Boolean patio, Boolean aguaCorriente, Boolean piscina, Boolean cloacas, Boolean gasNatural, Boolean pavimento, Boolean lavadero, Boolean aguaCaliente, Integer telefono, Set inmuebles) {
       this.idEdificio = idEdificio;
       this.propiedadHorizontal = propiedadHorizontal;
       this.antiguedad = antiguedad;
       this.superficie = superficie;
       this.banios = banios;
       this.garage = garage;
       this.patio = patio;
       this.aguaCorriente = aguaCorriente;
       this.piscina = piscina;
       this.cloacas = cloacas;
       this.gasNatural = gasNatural;
       this.pavimento = pavimento;
       this.lavadero = lavadero;
       this.aguaCaliente = aguaCaliente;
       this.telefono = telefono;
       this.inmuebles = inmuebles;
    }
   
    public int getIdEdificio() {
        return this.idEdificio;
    }
    
    public void setIdEdificio(int idEdificio) {
        this.idEdificio = idEdificio;
    }
    public Boolean getPropiedadHorizontal() {
        return this.propiedadHorizontal;
    }
    
    public void setPropiedadHorizontal(Boolean propiedadHorizontal) {
        this.propiedadHorizontal = propiedadHorizontal;
    }
    public Integer getAntiguedad() {
        return this.antiguedad;
    }
    
    public void setAntiguedad(Integer antiguedad) {
        this.antiguedad = antiguedad;
    }
    public Integer getSuperficie() {
        return this.superficie;
    }
    
    public void setSuperficie(Integer superficie) {
        this.superficie = superficie;
    }
    public Integer getBanios() {
        return this.banios;
    }
    
    public void setBanios(Integer banios) {
        this.banios = banios;
    }
    public Boolean getGarage() {
        return this.garage;
    }
    
    public void setGarage(Boolean garage) {
        this.garage = garage;
    }
    public Boolean getPatio() {
        return this.patio;
    }
    
    public void setPatio(Boolean patio) {
        this.patio = patio;
    }
    public Boolean getAguaCorriente() {
        return this.aguaCorriente;
    }
    
    public void setAguaCorriente(Boolean aguaCorriente) {
        this.aguaCorriente = aguaCorriente;
    }
    public Boolean getPiscina() {
        return this.piscina;
    }
    
    public void setPiscina(Boolean piscina) {
        this.piscina = piscina;
    }
    public Boolean getCloacas() {
        return this.cloacas;
    }
    
    public void setCloacas(Boolean cloacas) {
        this.cloacas = cloacas;
    }
    public Boolean getGasNatural() {
        return this.gasNatural;
    }
    
    public void setGasNatural(Boolean gasNatural) {
        this.gasNatural = gasNatural;
    }
    public Boolean getPavimento() {
        return this.pavimento;
    }
    
    public void setPavimento(Boolean pavimento) {
        this.pavimento = pavimento;
    }
    public Boolean getLavadero() {
        return this.lavadero;
    }
    
    public void setLavadero(Boolean lavadero) {
        this.lavadero = lavadero;
    }
    public Boolean getAguaCaliente() {
        return this.aguaCaliente;
    }
    
    public void setAguaCaliente(Boolean aguaCaliente) {
        this.aguaCaliente = aguaCaliente;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


