package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Localidad generated by hbm2java
 */
public class Localidad  implements java.io.Serializable {


     private int idLocalidad;
     private Provincia provincia;
     private String nombre;
     private Set barrios = new HashSet(0);

    public Localidad() {
    }

	
    public Localidad(int idLocalidad, Provincia provincia) {
        this.idLocalidad = idLocalidad;
        this.provincia = provincia;
    }
    public Localidad(int idLocalidad, Provincia provincia, String nombre, Set barrios) {
       this.idLocalidad = idLocalidad;
       this.provincia = provincia;
       this.nombre = nombre;
       this.barrios = barrios;
    }
   
    public int getIdLocalidad() {
        return this.idLocalidad;
    }
    
    public void setIdLocalidad(int idLocalidad) {
        this.idLocalidad = idLocalidad;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getBarrios() {
        return this.barrios;
    }
    
    public void setBarrios(Set barrios) {
        this.barrios = barrios;
    }




}


