package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
public class Propietario  implements java.io.Serializable {


     private int idPropietario;
     private TipoDoc tipoDoc;
     private String nombre;
     private String apellido;
     private Integer telefono;
     private String email;
     private Integer nroDoc;
     private String calle;
     private Integer nroCalle;
     private Date fechaNacimiento;
     private Set inmuebles = new HashSet(0);

    public Propietario() {
    }

	
    public Propietario(int idPropietario, TipoDoc tipoDoc) {
        this.idPropietario = idPropietario;
        this.tipoDoc = tipoDoc;
    }
    public Propietario(int idPropietario, TipoDoc tipoDoc, String nombre, String apellido, Integer telefono, String email, Integer nroDoc, String calle, Integer nroCalle, Date fechaNacimiento, Set inmuebles) {
       this.idPropietario = idPropietario;
       this.tipoDoc = tipoDoc;
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
       this.email = email;
       this.nroDoc = nroDoc;
       this.calle = calle;
       this.nroCalle = nroCalle;
       this.fechaNacimiento = fechaNacimiento;
       this.inmuebles = inmuebles;
    }
   
    public int getIdPropietario() {
        return this.idPropietario;
    }
    
    public void setIdPropietario(int idPropietario) {
        this.idPropietario = idPropietario;
    }
    public TipoDoc getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(TipoDoc tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getNroDoc() {
        return this.nroDoc;
    }
    
    public void setNroDoc(Integer nroDoc) {
        this.nroDoc = nroDoc;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNroCalle() {
        return this.nroCalle;
    }
    
    public void setNroCalle(Integer nroCalle) {
        this.nroCalle = nroCalle;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getInmuebles() {
        return this.inmuebles;
    }
    
    public void setInmuebles(Set inmuebles) {
        this.inmuebles = inmuebles;
    }




}


