package Modelo;
// Generated 21-oct-2016 15:21:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDoc generated by hbm2java
 */
public class TipoDoc  implements java.io.Serializable {


     private int idTipoDoc;
     private String nombre;
     private Set propietarios = new HashSet(0);
     private Set vendedors = new HashSet(0);

    public TipoDoc() {
    }

	
    public TipoDoc(int idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public TipoDoc(int idTipoDoc, String nombre, Set propietarios, Set vendedors) {
       this.idTipoDoc = idTipoDoc;
       this.nombre = nombre;
       this.propietarios = propietarios;
       this.vendedors = vendedors;
    }
   
    public int getIdTipoDoc() {
        return this.idTipoDoc;
    }
    
    public void setIdTipoDoc(int idTipoDoc) {
        this.idTipoDoc = idTipoDoc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPropietarios() {
        return this.propietarios;
    }
    
    public void setPropietarios(Set propietarios) {
        this.propietarios = propietarios;
    }
    public Set getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set vendedors) {
        this.vendedors = vendedors;
    }




}


